# Generated by Django 5.1.4 on 2024-12-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_estudante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
