# Generated by Django 5.1.3 on 2024-11-11 01:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('cod_inter', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=255)),
                ('tipo', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
